"""
Liveness / anti-spoofing endpoints.

POST /api/liveness/verify
    Unauthenticated kiosk endpoint.
    Accepts a burst of base64 frames + optional metadata.
    Runs four-factor MediaPipe liveness analysis and logs any spoof attempt.

GET  /api/liveness/spoof-logs
    Admin-only endpoint to review logged spoof attempts.
"""
from __future__ import annotations

import logging
import time
from typing import Annotated, Optional

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from pydantic import BaseModel, Field
from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import Employee, SpoofLog
from app.routers.auth import get_current_user
from app.services.face_service import decode_frame
from app.services.liveness_service import check_liveness

DbDep    = Annotated[AsyncSession, Depends(get_db)]
AuthDep  = Annotated[None, Depends(get_current_user)]

logger = logging.getLogger(__name__)
router = APIRouter()

MIN_FRAMES = 3
MAX_FRAMES = 8
MAX_FRAME_AGE_S = 90   # reject payloads whose client timestamp is older than 90 s


# ── Request / Response schemas ────────────────────────────────────────────────

class LivenessRequest(BaseModel):
    frames: Annotated[list[str], Field(min_length=MIN_FRAMES, max_length=MAX_FRAMES)]
    # ISO-8601 ms timestamp generated by the client just before sending.
    # Used to detect replay attacks (old frames re-submitted).
    client_ts_ms: Optional[int] = None
    # Which challenge was shown to the user when frames were collected.
    challenge: Optional[str] = None
    # challenge_passed is set by the frontend after its own pixel-diff check.
    challenge_passed: Optional[bool] = None
    # Optional employee id so the spoof log can reference the recognised employee.
    employee_db_id: Optional[str] = None


class LivenessResponse(BaseModel):
    is_live:    bool
    confidence: float
    reason:     str
    message:    str
    scores:     Optional[dict] = None


# ── Helpers ───────────────────────────────────────────────────────────────────

def _client_ip(request: Request) -> str:
    forwarded = request.headers.get("x-forwarded-for")
    if forwarded:
        return forwarded.split(",")[0].strip()
    if request.client:
        return request.client.host
    return "unknown"


async def _log_spoof(
    db: AsyncSession,
    reason: str,
    confidence: float,
    ip: str,
    challenge: Optional[str],
    frame_count: int,
    employee_db_id: Optional[str],
) -> None:
    """Persist one spoof attempt to the spoof_logs table."""
    try:
        entry = SpoofLog(
            reason=reason,
            confidence=round(confidence, 4),
            ip_address=ip,
            challenge=challenge,
            frame_count=frame_count,
            employee_db_id=employee_db_id or None,
        )
        db.add(entry)
        await db.commit()
        logger.warning(
            "SPOOF DETECTED | reason=%s conf=%.3f ip=%s challenge=%s emp=%s",
            reason, confidence, ip, challenge, employee_db_id,
        )
    except Exception as exc:
        logger.error("Failed to write spoof log: %s", exc)


# ── POST /verify ──────────────────────────────────────────────────────────────

@router.post("/verify", responses={422: {"description": "Fewer than 3 decodable frames provided"}})
async def verify_liveness(
    payload: LivenessRequest,
    request: Request,
    db: DbDep,
) -> LivenessResponse:
    """
    Verify liveness of a burst of webcam frames.

    Security layers applied in order:
      1. Replay prevention  — reject payloads with a stale client timestamp.
      2. Challenge check    — if the frontend flagged challenge_passed=False, block immediately.
      3. MediaPipe analysis — four-factor score (EAR, nose, plausibility, texture).
      4. Spoof logging      — any failed check is written to spoof_logs.
    """
    ip = _client_ip(request)

    # ── Layer 1: Replay prevention ────────────────────────────────────────────
    if payload.client_ts_ms is not None:
        age_s = (time.time() * 1000 - payload.client_ts_ms) / 1000
        if age_s > MAX_FRAME_AGE_S or age_s < -10:
            await _log_spoof(
                db, "replay_attack", 0.0, ip,
                payload.challenge, len(payload.frames), payload.employee_db_id,
            )
            return LivenessResponse(
                is_live=False, confidence=0.0,
                reason="replay_attack",
                message="Replay attack detected — timestamp too old.",
            )

    # ── Layer 2: Frontend challenge result ────────────────────────────────────
    if payload.challenge_passed is False:
        await _log_spoof(
            db, "challenge_fail", 0.0, ip,
            payload.challenge, len(payload.frames), payload.employee_db_id,
        )
        return LivenessResponse(
            is_live=False, confidence=0.0,
            reason="challenge_fail",
            message=f"Challenge not completed: {payload.challenge or 'unknown'}",
        )

    # ── Decode frames ─────────────────────────────────────────────────────────
    decoded: list[np.ndarray] = []
    for b64 in payload.frames:
        frame = decode_frame(b64)
        if frame is not None:
            decoded.append(frame)

    if len(decoded) < MIN_FRAMES:
        raise HTTPException(
            status_code=422,
            detail=f"At least {MIN_FRAMES} decodable frames required; got {len(decoded)}.",
        )

    # ── Layer 3: MediaPipe four-factor analysis ───────────────────────────────
    try:
        result = check_liveness(decoded)
    except Exception as exc:
        # Fail open: backend errors must never permanently lock out real employees.
        logger.exception("check_liveness raised: %s", exc)
        result = {"is_live": True, "confidence": 0.5, "reason": "live", "scores": {}}

    is_live    = result["is_live"]
    confidence = result["confidence"]
    reason     = result["reason"]
    scores     = result.get("scores", {})

    # ── Layer 4: Spoof logging ────────────────────────────────────────────────
    if not is_live:
        await _log_spoof(
            db, reason, confidence, ip,
            payload.challenge, len(decoded), payload.employee_db_id,
        )

    message_map = {
        "live":                "✅ Liveness confirmed.",
        "static_image":        "⚠️ Spoofing detected — static image or screen replay not allowed.",
        "no_face_detected":    "Face not clearly visible. Please look directly at the camera.",
        "insufficient_frames": "Not enough frames collected. Please hold still.",
        "replay_attack":       "Replay attack detected.",
        "challenge_fail":      "Challenge not completed.",
    }

    return LivenessResponse(
        is_live=is_live,
        confidence=confidence,
        reason=reason,
        message=message_map.get(reason, "Liveness check complete."),
        scores=scores,
    )


# ── GET /spoof-logs  (admin only) ─────────────────────────────────────────────

@router.get("/spoof-logs")
async def spoof_logs(
    skip:  Annotated[int, Query(ge=0)]         = 0,
    limit: Annotated[int, Query(ge=1, le=500)] = 100,
    db:    DbDep                               = None,
    _:     AuthDep                             = None,
):
    """
    Return paginated spoof-attempt log entries for admin review.
    Ordered newest-first.
    """
    q = (
        select(SpoofLog, Employee)
        .outerjoin(Employee, SpoofLog.employee_db_id == Employee.id)
        .order_by(desc(SpoofLog.timestamp))
        .offset(skip)
        .limit(limit)
    )
    rows = (await db.execute(q)).all()

    return [
        {
            "id":              str(log.id),
            "timestamp":       log.timestamp.isoformat() if log.timestamp else None,
            "reason":          log.reason,
            "confidence":      float(log.confidence) if log.confidence is not None else None,
            "challenge":       log.challenge,
            "ip_address":      log.ip_address,
            "frame_count":     log.frame_count,
            "employee_id":     emp.employee_id if emp else None,
            "employee_name":   emp.name        if emp else None,
        }
        for log, emp in rows
    ]
